### ISSUE TITLE
Creation of separate plugins

### ISSUE THREAD

**Issue by vitalielias** [kit-data-manager/SEMplugin#3]
The current library is limited in producing only one single plugin, it needs to somehow be modified to either combine plugins or we need separate versions of the code for each plugin.

Even if the parameters are changed, the generated plugin is not recognized as different by the mapping service, therefore the way it is built needs to be changed.

**Comment by reetuelzajoseph** [comment]
Did you try cloning the repository and changing the `build.gradle` and `settings.gradle`  to reflect with the name of your new root project, which contains the code (.java) for the second plugin?

**Comment by vitalielias** [comment]
I believe that's what I have to do, just haven't yet had the chance. I will report back :)
